Calendar modal & Date picker
Hexsnorth12/TicketSystem-frontend pull request #136
Opened 2024-06-03 18:48 UTC by JohnnyHsu041

Resolve #93 #97

1. 新增我的揪團路由
2. 安裝新material UI套件：@mui/x-date-pickers
3. 建立日期選擇彈窗
4. 建立日期＆時間選擇欄位

使用material UI套件來建立，樣式沒有完全符合設計稿
日期選擇原本要用套件中的'DateRangePicker'，但是要收錢，不然會有很醜的浮水印

Border屬性調整的位置有點難找，這部分uncompleted，先使用套件原本的預設樣式。日後會再修

![截圖 2024-06-04 上午2 45 36](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/87815117/fba03cce-c90b-4077-894a-2c60661ff5fb)
![截圖 2024-06-04 上午2 45 24](https://github.com/Hexsnorth12/TicketSystem-frontend/assets/87815117/4bab76d3-3abd-4962-af2f-e6c439c58db7)

2024-06-03 23:13 UTC, viss5vuus98 approved these changes
ok

2024-06-03 23:17 UTC, viss5vuus98 requested changes
modal 關掉時會跳回上一頁

2024-06-04 02:04 UTC, muchuanhung approved these changes
ok

2024-06-04 03:29 UTC, wen1011 approved these changes
ok ~ conflicts that must be resolved

2024-06-05 17:56 UTC, JohnnyHsu041 commented
> modal 關掉時會預設跳回上一頁，可以用 pr #134 作法 把modal 頁放在@modal 裡

fixed

2024-06-06 01:38 UTC, viss5vuus98 approved these changes

2024-06-06 01:38 UTC, merged