Feat/share tickets
Hexsnorth12/TicketSystem-frontend pull request #203
Opened 2024-06-18 04:56 UTC by viss5vuus98

1. 新增會員分票列表
2. 分票及上架功能未完成先關閉按鈕

2024-06-18 05:09 UTC, muchuanhung approved these changes
ok

2024-06-18 05:10 UTC, muchuanhung requested changes
ci 跟 vercel沒過 在check一下

2024-06-18 15:59 UTC, muchuanhung approved these changes

2024-06-19 14:03 UTC, wen1011 approved these changes
ok

2024-06-19 14:03 UTC, merged