fix: google login error issue
Hexsnorth12/TicketSystem-frontend pull request #286
Opened 2024-07-04 16:15 UTC by muchuanhung

#217

- 修復google登入 可以正常使用我的收藏，我的分票，我的揪團等功能
- google登入後也會自動導向首頁
-
<img width="1334" alt="截圖 2024-07-05 上午12 08 42" src="https://github.com/Hexsnorth12/TicketSystem-frontend/assets/61078091/150cd392-5004-494d-83b4-8b72bf65a482">

2024-07-05 02:09 UTC, viss5vuus98 requested changes

2024-07-05 02:09 UTC, viss5vuus98 commented on src/components/forms/SignIn/signIn.tsx
> +    }, [session, status, searchParams, router])
這個做法討論下

2024-07-05 12:51 UTC, wen1011 approved these changes
先ok等你跟jule討論完

2024-07-05 15:17 UTC, muchuanhung commented
改完囉 在確認一下

2024-07-06 02:07 UTC, viss5vuus98 approved these changes
ok

2024-07-06 02:08 UTC, merged